merged src and bin install

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -144,11 +144,9 @@ write_config() {
     > "${qtconfig_pri}"
 }
 
-main() {
-  local install_type=$1
-  local version=$2
-  local install_path=$3
-  local download_path=$4
+download_binary() {
+  local version=$1
+  local download_path=$2
 
   tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/asdf-qt-XXXXXXXXXX")
 
@@ -192,6 +190,40 @@ main() {
   write_config "${tmp_dir}/${number}/$(compiler)"
 
   mv "${tmp_dir}/${number}/$(compiler)"/* "${download_path}"
+}
+
+download_src() {
+  local version=$1
+  local download_path=$2
+
+  tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/asdf-qt-XXXXXXXXXX")
+
+  # cleanup on failures
+  trap "rm -rf $tmp_dir" EXIT
+  trap "rm -rf $download_path" ERR
+
+  git clone git://code.qt.io/qt/qt5.git $tmp_dir
+  cd $tmp_dir
+  git checkout "${version}"
+  perl init-repository -f
+
+  mv "${tmp_dir}"/* "${download_path}"
+}
+
+main() {
+  local install_type=$1
+  local version=$2
+  local install_path=$3
+  local download_path=$4
+
+  if [[ $install_type == "version" ]]; then
+    download_binary "$version" "$download_path"
+  elif [[ $install_type == "ref" ]]; then
+    download_src "$version" "$download_path"
+  else
+    echo "Unknown install type: $install_type"
+    exit 1
+  fi
 }
 
 if [ -z "$ASDF_INSTALL_TYPE" ]; then
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -3,46 +3,26 @@
 set -eE
 set -o pipefail
 
-clone_repo() {
+build() {
   local src_dir=$1
-  local version=$2
+  local install_dir=$2
+  local n_cores=$3
 
-  # drop the -dev from the version number (if exists)
-  number=${version%"-dev"}
+  tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/asdf-qt-XXXXXXXXXX")
 
-  git clone git://code.qt.io/qt/qt5.git $src_dir
-  cd $src_dir
-  git checkout "v${number}"
-  perl init-repository -f
-}
+  # cleanup on failures
+  trap "rm -rf $tmp_dir" EXIT
+  trap "rm -rf $install_dir" ERR
 
-install() {
-  local src_dir=$1
-  local build_dir=$2
-  local install_dir=$3
-  local n_cores=$4
-  local version=$5
+  cd $tmp_dir
 
-  mkdir $build_dir
-  cd $build_dir
-
-  if [[ $version == *"-dev" ]]
-  then
-    $src_dir/configure \
-      -developer-build \
-      -prefix $install_dir \
-      -opensource \
-      -confirm-license \
-      -nomake examples \
-      -nomake tests
-  else
-    $src_dir/configure \
-      -prefix $install_dir \
-      -opensource \
-      -confirm-license \
-      -nomake examples \
-      -nomake tests
-  fi
+  $src_dir/configure \
+    -developer-build \
+    -prefix $install_dir \
+    -opensource \
+    -confirm-license \
+    -nomake examples \
+    -nomake tests
 
   make -j$n_cores
   make install
@@ -51,20 +31,18 @@ install() {
 main() {
   local install_type=$1
   local version=$2
-  local install_path=$3
-  local n_cores=$4
+  local download_path=$3
+  local install_path=$4
+  local n_cores=$5
 
-  tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/asdf-qt-XXXXXXXXXX")
-
-  # cleanup on failures
-  trap "rm -rf $tmp_dir" EXIT
-  trap "rm -rf $install_path" ERR
-
-  src_dir="$tmp_dir/src"
-  clone_repo $src_dir $version
-
-  build_dir="$tmp_dir/build"
-  install $src_dir $build_dir $install_path $n_cores $version
+  if [[ $install_type == "ref" ]]; then
+    mv "${download_path}"/* "${install_path}"
+  elif [[ $install_type == "ref" ]]; then
+    install "${download_path}" "${install_path}" "${n_cores}"
+  else
+    echo "Unknown install type: $install_type"
+    exit 1
+  fi
 }
 
-main $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH $ASDF_CONCURRENCY
+main $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_DOWNLOAD_PATH $ASDF_INSTALL_PATH $ASDF_CONCURRENCY
